name: CI - Train Telco Churn Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn==1.9.0 pandas numpy

      - name: Run MLflow Project
        working-directory: MLProject
        run: |
          mlflow run . --env-manager=local

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mlruns
          path: MLProject/mlruns/
