name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo "Struktur folder GitHub Actions berhasil dibuat dan berjalan aman!"
